version: '3'

services:
  db:
    container_name: old-system-container
    restart: always
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_DB=old-system-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5445:5432"