version: '3'

services:
  db:
    container_name: new-system-container
    restart: always
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_DB=new-system-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5444:5432"