name: cleverdev-systems

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: install maven
        run: |
          sudo apt-get install maven

      - name: build old system
        run: |
          cd old-system
          mvn clean package  

      - name: build new system
        run: |
          cd new-system
          mvn clean package
